-- Nityaseva | CareNest Service Master v3
-- Run AFTER carenest_supabase_v1.sql has completed successfully.
-- IMPORTANT: service_categories does NOT have a `code` column in the schema.
-- This version matches the actual v1 schema and is safe to re-run.

begin;

-- ------------------------------------------------------------
-- 1. SERVICE CATEGORIES
-- ------------------------------------------------------------
insert into public.service_categories (name, description)
values
 ('Wellbeing','Senior wellbeing and routine checks'),
 ('Health','Health measurements and clinical coordination'),
 ('Medicine','Medicine support'),
 ('Essentials','Grocery and household support'),
 ('Appointments','Doctor, lab and appointment coordination'),
 ('Hospital','Hospital coordination and escort'),
 ('Emergency','Emergency coordination'),
 ('Mobility','Escort and physiotherapy support'),
 ('Technology','Technology assistance'),
 ('Administration','Documents and bill assistance'),
 ('Care','Nursing and attendant coordination')
on conflict (name) do update
set description = excluded.description;

-- ------------------------------------------------------------
-- 2. SERVICES
-- category_id is resolved from service_categories.name.
-- ------------------------------------------------------------
insert into public.services
(service_code, service_name, category_id, description, customer_gets,
 representative_does, not_included, escalation_rule, price, pricing_type,
 duration_minutes, requires_approval, requires_professional, active)
select v.service_code, v.service_name, c.id, v.description, v.customer_gets,
       v.representative_does, v.not_included, v.escalation_rule, v.price,
       v.pricing_type, v.duration_minutes, v.requires_approval,
       v.requires_professional, true
from (values
 ('WELL-001','Senior Wellbeing Check','Wellbeing',
  'Routine in-person wellbeing observation and conversation.',
  'A structured wellbeing check and family update.',
  'Observe general wellbeing, food, hydration, mood, mobility and immediate concerns; record and report.',
  'No diagnosis, prescription, treatment or medical interpretation.',
  'Escalate urgent or concerning findings to the family/care manager and qualified medical or emergency services as appropriate.',
  null::numeric,'included',30,false,false),
 ('HLT-001','Basic Health Measurements','Health',
  'Non-diagnostic recording of basic health measurements.',
  'Recorded BP, pulse, SpO2, temperature and/or glucose when appropriate equipment is available.',
  'Take and record measurements within training/scope and report abnormal or concerning observations.',
  'No diagnosis, clinical interpretation or medication changes.',
  'Concerning readings are escalated to a qualified professional/family; emergencies are handled through emergency services first.',
  null::numeric,'included',20,false,false),
 ('MED-001','Medicine Availability Check','Medicine',
  'Check whether required medicines appear available at home.',
  'A medicine-availability status update.',
  'Check availability and flag missing/low supplies without changing prescriptions.',
  'No prescribing, dose changes or clinical medication advice.',
  'Missing/unclear medication information is escalated to family and/or qualified clinician.',
  null::numeric,'included',15,false,false),
 ('MED-002','Medicine Pickup','Medicine',
  'Pickup of medicines from an authorized pharmacy.',
  'Medicine pickup and delivery to the senior/home.',
  'Collect and deliver medicines against an authorized prescription/order.',
  'Medicine cost; prescription changes; controlled-substance handling outside applicable procedures.',
  'Prescription or medicine issue is escalated to family/pharmacy/doctor.',
  199,'addon',45,false,false),
 ('ESS-001','Grocery/Essential Pickup','Essentials',
  'Pickup and delivery of agreed groceries or household essentials.',
  'Requested essentials delivered to the senior/home.',
  'Purchase/pickup and deliver agreed items; retain bill where applicable.',
  'Product cost; restricted goods; financial transactions requiring confidential credentials.',
  'Unavailable item, price issue or safety concern is reported before substitution where approval is needed.',
  199,'addon',60,false,false),
 ('APT-001','Doctor Appointment Coordination','Appointments',
  'Coordinate doctor appointment scheduling and reminders.',
  'Appointment arranged and details shared with family/senior.',
  'Coordinate booking, confirmation, reminders and relevant logistics.',
  'Medical diagnosis or treatment advice.',
  'Urgent symptoms are escalated immediately; do not wait for routine appointment scheduling.',
  null::numeric,'included',30,false,false),
 ('APT-002','Doctor Home Visit','Appointments',
  'Coordinate a qualified doctor home visit through a partner.',
  'Doctor visit coordination at home.',
  'Coordinate availability, address, timing and family communication.',
  'Doctor consultation fee and any treatment prescribed by the doctor.',
  'Emergency conditions bypass routine home-visit coordination and use emergency services.',
  null::numeric,'partner_actual',60,true,true),
 ('APT-003','Lab Test Coordination','Appointments',
  'Coordinate home/sample-collection or laboratory testing through a qualified partner.',
  'Lab appointment and report coordination.',
  'Schedule collection/test and share status/report availability.',
  'Lab charges and clinical interpretation.',
  'Urgent clinical concerns are escalated to qualified medical care.',
  null::numeric,'partner_actual',30,true,true),
 ('MOB-001','Physiotherapy','Mobility',
  'Coordinate physiotherapy through a qualified professional.',
  'Scheduled physiotherapy session.',
  'Coordinate appointment and logistics with a qualified physiotherapist.',
  'Professional fee and clinical treatment outside the agreed session.',
  'Acute deterioration or emergency symptoms are escalated to medical/emergency services.',
  699,'addon',60,true,true),
 ('HOS-001','Hospital Coordination','Hospital',
  'Coordinate hospital logistics and family communication.',
  'Hospital coordination support and updates.',
  'Coordinate admission/visit logistics, documents and family updates within role scope.',
  'Hospital bills, treatment decisions and clinical care.',
  'Emergency-first: call emergency services/ambulance immediately when required.',
  799,'addon',120,true,false),
 ('EMR-001','Emergency Coordination','Emergency',
  'Immediate coordination support during a senior emergency.',
  'Emergency escalation and family communication support.',
  'Call appropriate emergency services, alert family/care manager, coordinate ambulance/hospital logistics and record the event.',
  'Does not replace emergency medical services or clinical treatment.',
  'Emergency services take priority; never delay emergency response for company approval.',
  null::numeric,'included',30,false,false),
 ('MOB-002','Appointment Escort','Mobility',
  'Escort and coordination support for an appointment.',
  'Safe appointment travel/onsite coordination within agreed scope.',
  'Escort senior, coordinate arrival/departure and family updates.',
  'Medical decisions, clinical procedures or transport requiring a specialized ambulance unless separately arranged.',
  'Emergency symptoms trigger emergency escalation rather than routine escort workflow.',
  699,'addon',180,true,false),
 ('SAFE-001','Home Safety Check','Wellbeing',
  'Basic non-clinical home safety observation.',
  'Safety observations and practical recommendations.',
  'Observe fall hazards, lighting, access, bathroom/bedroom risks and emergency readiness.',
  'Construction/repair work and regulated safety inspections.',
  'Immediate hazards are escalated to family/care manager for urgent action.',
  null::numeric,'included',30,false,false),
 ('WELL-002','Food & Hydration Check','Wellbeing',
  'Routine observation of food and hydration availability/consumption.',
  'Food/hydration status included in the visit report.',
  'Observe availability and encourage routine hydration/food as appropriate.',
  'Diet plans, nutritional diagnosis or clinical advice.',
  'Poor intake or concerning symptoms are escalated to family and qualified professionals.',
  null::numeric,'included',15,false,false),
 ('FAM-001','Family Connection','Wellbeing',
  'Facilitate a scheduled family call or video connection.',
  'Help maintaining family connection.',
  'Assist with device setup/call connection when requested.',
  'No guarantee of family availability or response.',
  'If the senior expresses urgent safety/health concerns, follow escalation SOP.',
  null::numeric,'included',20,false,false),
 ('TECH-001','Technology Assistance','Technology',
  'Basic assistance with phone, video calls, apps and device settings.',
  'Practical technology help.',
  'Assist with basic settings, calls, app navigation and device use.',
  'Passwords, OTPs, UPI PINs, ATM PINs, banking credentials or unauthorized financial actions.',
  'Escalate suspected fraud, account compromise or unsafe request to family/appropriate authority.',
  299,'addon',45,false,false),
 ('ADM-001','Bill/Document Assistance','Administration',
  'Basic help organizing bills and documents.',
  'Documents/bills organized or prepared for family follow-up.',
  'Collect, scan/organize and communicate documents within agreed scope.',
  'Banking credentials, OTPs, PINs, signing legal documents or making unauthorized payments.',
  'Financial/legal concerns are escalated to the family and appropriate professional.',
  299,'addon',45,false,false),
 ('CARE-001','Nurse Visit','Care',
  'Coordinate a qualified nurse visit through an appropriate professional.',
  'Professional nursing visit.',
  'Coordinate scheduling and family communication with qualified nurse.',
  'Professional fee and services outside the nurse scope/contract.',
  'Emergency conditions bypass routine nursing coordination.',
  1000,'addon',60,true,true),
 ('CARE-002','Attendant Service','Care',
  'Coordinate a trained attendant for agreed non-clinical support.',
  'Attendant support for the agreed period.',
  'Coordinate roster, timing and basic assistance within role scope.',
  'Clinical procedures, medication administration outside authorization/scope and unrestricted personal financial handling.',
  'Staff safety or senior deterioration is escalated immediately.',
  1000,'addon',480,true,false),
 ('CARE-003','Post-Hospital Recovery Coordination','Care',
  'Coordinate post-hospital home support and follow-up logistics.',
  'Structured recovery-support coordination.',
  'Coordinate visits, appointments, medication availability checks and family updates.',
  'Clinical treatment or independent medication changes.',
  'Any deterioration or emergency symptom is escalated to qualified medical/emergency care.',
  999,'addon',120,true,false),
 ('CARE-004','Nityaseva Extra Visit','Care',
  'Additional care visit outside included monthly plan visits.',
  'Extra in-person support visit.',
  'Conduct standard visit/checklist and communicate findings.',
  'Clinical diagnosis/treatment and services outside agreed scope.',
  'Escalate emergencies immediately.',
  399,'addon',45,false,false),
 ('CARE-005','Care Manager Visit','Care',
  'Higher-level care review by the Care Manager.',
  'Care plan review and family coordination.',
  'Review service history, risks, requests and next steps.',
  'Medical diagnosis or treatment.',
  'Clinical concerns are escalated to qualified professionals.',
  699,'addon',60,false,false),
 ('SAFE-002','Senior Safety Kit','Wellbeing',
  'Optional home safety and monitoring kit.',
  'Safety kit supplied and recorded.',
  'Supply/configure agreed kit items and provide basic usage orientation.',
  'Clinical interpretation of readings or replacement consumables unless separately agreed.',
  'Equipment issue is escalated for replacement/service.',
  4999,'addon',30,true,false),
 ('REP-001','Monthly Family Report','Administration',
  'Structured monthly summary for the family.',
  'Monthly care and activity report.',
  'Compile visit completion, wellbeing observations, services, incidents, attention items and next steps.',
  'Independent medical diagnosis or interpretation.',
  'Critical incidents are communicated immediately and not held for the monthly report.',
  null::numeric,'included',60,false,false),
 ('SUP-001','Customer Support','Administration',
  'Customer support for service questions and coordination.',
  'Support request handling and status updates.',
  'Receive, classify, assign and follow up service/customer issues.',
  'Emergency medical care and clinical advice.',
  'Emergency requests are routed to emergency services immediately.',
  null::numeric,'included',30,false,false)
) as v(service_code,service_name,category_name,description,customer_gets,representative_does,not_included,escalation_rule,price,pricing_type,duration_minutes,requires_approval,requires_professional)
join public.service_categories c on c.name = v.category_name
on conflict (service_code) do update set
 service_name = excluded.service_name,
 category_id = excluded.category_id,
 description = excluded.description,
 customer_gets = excluded.customer_gets,
 representative_does = excluded.representative_does,
 not_included = excluded.not_included,
 escalation_rule = excluded.escalation_rule,
 price = excluded.price,
 pricing_type = excluded.pricing_type,
 duration_minutes = excluded.duration_minutes,
 requires_approval = excluded.requires_approval,
 requires_professional = excluded.requires_professional,
 active = excluded.active,
 updated_at = now();

-- ------------------------------------------------------------
-- 3. PLAN INCLUSIONS
-- ------------------------------------------------------------
with inclusion(service_code, plan_code, included, monthly_limit) as (
 values
 ('WELL-001','SAFE',true,2),('WELL-001','CARE',true,4),('WELL-001','PRIORITY',true,8),
 ('HLT-001','SAFE',true,2),('HLT-001','CARE',true,4),('HLT-001','PRIORITY',true,8),
 ('MED-001','SAFE',true,2),('MED-001','CARE',true,4),('MED-001','PRIORITY',true,8),
 ('APT-001','SAFE',true,1),('APT-001','CARE',true,2),('APT-001','PRIORITY',true,4),
 ('EMR-001','SAFE',true,999),('EMR-001','CARE',true,999),('EMR-001','PRIORITY',true,999),
 ('SAFE-001','SAFE',true,1),('SAFE-001','CARE',true,1),('SAFE-001','PRIORITY',true,2),
 ('WELL-002','SAFE',true,2),('WELL-002','CARE',true,4),('WELL-002','PRIORITY',true,8),
 ('FAM-001','SAFE',true,2),('FAM-001','CARE',true,4),('FAM-001','PRIORITY',true,8),
 ('REP-001','SAFE',true,1),('REP-001','CARE',true,1),('REP-001','PRIORITY',true,1),
 ('SUP-001','SAFE',true,999),('SUP-001','CARE',true,999),('SUP-001','PRIORITY',true,999),
 ('MED-002','SAFE',false,null),('MED-002','CARE',false,null),('MED-002','PRIORITY',false,null),
 ('ESS-001','SAFE',false,null),('ESS-001','CARE',false,null),('ESS-001','PRIORITY',false,null),
 ('APT-002','SAFE',false,null),('APT-002','CARE',false,null),('APT-002','PRIORITY',false,null),
 ('APT-003','SAFE',false,null),('APT-003','CARE',false,null),('APT-003','PRIORITY',false,null),
 ('MOB-001','SAFE',false,null),('MOB-001','CARE',false,null),('MOB-001','PRIORITY',false,null),
 ('HOS-001','SAFE',false,null),('HOS-001','CARE',false,null),('HOS-001','PRIORITY',false,null),
 ('MOB-002','SAFE',false,null),('MOB-002','CARE',false,null),('MOB-002','PRIORITY',false,null),
 ('TECH-001','SAFE',false,null),('TECH-001','CARE',false,null),('TECH-001','PRIORITY',false,null),
 ('ADM-001','SAFE',false,null),('ADM-001','CARE',false,null),('ADM-001','PRIORITY',false,null),
 ('CARE-001','SAFE',false,null),('CARE-001','CARE',false,null),('CARE-001','PRIORITY',false,null),
 ('CARE-002','SAFE',false,null),('CARE-002','CARE',false,null),('CARE-002','PRIORITY',false,null),
 ('CARE-003','SAFE',false,null),('CARE-003','CARE',false,null),('CARE-003','PRIORITY',false,null),
 ('CARE-004','SAFE',false,null),('CARE-004','CARE',false,null),('CARE-004','PRIORITY',false,null),
 ('CARE-005','SAFE',false,null),('CARE-005','CARE',false,null),('CARE-005','PRIORITY',false,null),
 ('SAFE-002','SAFE',false,null),('SAFE-002','CARE',false,null),('SAFE-002','PRIORITY',false,null)
)
insert into public.service_plan_inclusions(service_id,plan_code,included,monthly_limit)
select s.id,i.plan_code,i.included,i.monthly_limit
from inclusion i join public.services s on s.service_code=i.service_code
on conflict(service_id,plan_code) do update set
 included=excluded.included,
 monthly_limit=excluded.monthly_limit;

commit;

-- Verification
select count(*) as service_category_count from public.service_categories;
select count(*) as service_count from public.services;
select count(*) as plan_inclusion_count from public.service_plan_inclusions;
