import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import './styles.css';

const URL=import.meta.env.VITE_SUPABASE_URL, KEY=import.meta.env.VITE_SUPABASE_ANON_KEY;
const LOGO=`${import.meta.env.BASE_URL}lotus-white.svg`;
const sb=URL&&KEY?createClient(URL,KEY):null;
const roles=['super_admin','admin','care_manager','care_executive','nurse','partner','family','senior'];
const admin=['super_admin','admin'];
const demoData={profile:{full_name:'Demo Admin',role:'super_admin'},seniors:[{id:'d1',customer_code:'NIT-001',full_name:'Mrs. Anima Banerjee',age:74,gender:'Female',phone:'+91 90000 00001',city:'Asansol',risk_level:'yellow',active:true},{id:'d2',customer_code:'NIT-002',full_name:'Mr. Subhash Sen',age:81,gender:'Male',phone:'+91 90000 00002',city:'Burnpur',risk_level:'green',active:true},{id:'d3',customer_code:'NIT-003',full_name:'Mrs. Mira Roy',age:78,gender:'Female',phone:'+91 90000 00003',city:'Asansol',risk_level:'red',active:true}],plans:[{id:'p1',code:'SAFE',name:'SAFE',single_price:1799,couple_price:2999,active:true},{id:'p2',code:'CARE',name:'CARE',single_price:3499,couple_price:5499,active:true},{id:'p3',code:'PRIORITY',name:'PRIORITY',single_price:5999,couple_price:8999,active:true}],visits:[],requests:[],health:[],incidents:[],subscriptions:[],payments:[],services:[],families:[],staff:[],notifications:[],reports:[]};
const nav=(role)=>role==='family'?['Home','My Parent','Visits','Health','Requests','Reports','Subscription','Notifications']:role==='senior'?['Home','Next Visit','Request Help','Emergency','Family']:role==='care_executive'?['Today','My Seniors','Visits','Requests','Emergency']:role==='nurse'?['Overview','Assigned Seniors','Health','Visits']:role==='care_manager'?['Overview','Seniors','Visits','Requests','Incidents','Reports']:role==='partner'?['Requests','Appointments']:['Overview','Seniors','Families','Staff','Visits','Requests','Health','Incidents','Emergency','Subscriptions','Payments','Reports','Services','Notifications','Settings'];
const icon={Overview:'⌂',Seniors:'♙',Families:'♧',Staff:'♟',Visits:'◷',Requests:'☷',Health:'♥',Incidents:'⚠',Emergency:'!',Subscriptions:'▣',Payments:'₹',Reports:'▤',Services:'✦',Notifications:'●',Settings:'⚙',Today:'◷','My Seniors':'♙','Assigned Seniors':'♙','My Parent':'♥','Next Visit':'◷','Request Help':'＋',Family:'♧',Home:'⌂',Support:'?',Appointments:'◷'};
function App(){
 const [profile,setProfile]=useState(null),[session,setSession]=useState(null),[loading,setLoading]=useState(true),[page,setPage]=useState('Overview'),[d,setD]=useState(demoData),[toast,setToast]=useState(''),[login,setLogin]=useState({email:'',password:''});
 const demo=!sb;
 useEffect(()=>{if(!sb){setProfile(demoData.profile);setD(structuredClone(demoData));setLoading(false);return}sb.auth.getSession().then(async({data})=>{setSession(data.session);if(data.session)await loadProfile(data.session.user.id);setLoading(false)});const l=sb.auth.onAuthStateChange(async(_,s)=>{setSession(s);if(s)await loadProfile(s.user.id);else setProfile(null)});return()=>l.data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session&&profile)loadAll()},[session,profile]);
 async function loadProfile(id){const {data,error}=await sb.from('profiles').select('*').eq('id',id).single();if(error)notify(error.message);else setProfile(data)}
 async function q(table,select='*',limit=500){const {data,error}=await sb.from(table).select(select).limit(limit);if(error){console.warn(table,error.message);return []}return data||[]}
 async function loadAll(){const [s,f,st,p,v,r,h,i,e,sub,pay,svc,n,rep]=await Promise.all([q('seniors'),q('family_members'),q('staff_assignments'),q('service_plans'),q('visits'),q('service_requests'),q('health_readings'),q('incidents'),q('emergency_events'),q('subscriptions'),q('payments'),q('services'),q('notifications'),q('family_reports')]);setD(x=>({...x,seniors:s,families:f,staff:st,plans:p,visits:v,requests:r,health:h,incidents:i,emergency:e,subscriptions:sub,payments:pay,services:svc,notifications:n,reports:rep}))}
 function notify(x){setToast(x);setTimeout(()=>setToast(''),3500)}
 async function loginUser(e){e.preventDefault();const {error}=await sb.auth.signInWithPassword(login);if(error)notify(error.message)}
 async function logout(){if(sb)await sb.auth.signOut();else setProfile(null)}
 if(loading)return <div className="center">Loading Nityaseva…</div>;
 if(!profile)return <Login login={login} setLogin={setLogin} onSubmit={loginUser} demo={demo} enter={()=>setProfile(demoData.profile)}/>;
 return <div className="app"><aside><div className="brand"><div className="logo"><img src={LOGO}/></div><div><b>Nityaseva</b><small>Eternal service, Timeless care.</small></div></div><div className="userbox"><b>{profile.full_name||profile.email||'User'}</b><span>{profile.role}</span></div><nav>{nav(profile.role).map(n=><button className={page===n?'active':''} onClick={()=>setPage(n)} key={n}><span>{icon[n]||'•'}</span>{n}</button>)}</nav><button className="logout" onClick={logout}>↪ Sign out</button></aside><main><header><div><h1>{page}</h1><p>{desc(page)}</p></div><div className="header-actions"><span className={demo?'demo':'live'}>● {demo?'DEMO MODE':'LIVE SUPABASE'}</span>{admin.includes(profile.role)&&<button className="primary" onClick={()=>setPage('Seniors')}>+ Add senior</button>}</div></header>{toast&&<div className="toast">{toast}</div>}<Page page={page} role={profile.role} d={d} refresh={loadAll} notify={notify}/></main></div>
}
function Login({login,setLogin,onSubmit,demo,enter}){return <div className="login"><div className="login-card"><div className="brand big"><div className="logo"><img src={LOGO}/></div><div><b>Nityaseva</b><small>Eternal service, Timeless care.</small></div></div><h1>Welcome back</h1><p>Trusted local care for seniors and their families.</p>{demo?<><div className="notice">Supabase is not configured. Demo mode is available.</div><button className="primary full" onClick={enter}>Enter demo dashboard</button></>:<form onSubmit={onSubmit}><label>Email<input type="email" required value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/></label><label>Password<input type="password" required value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/></label><button className="primary full">Sign in</button></form>}<small className="muted">Browser uses only the Supabase anon/publishable key. Never expose service-role secrets.</small></div></div>}
function Page({page,role,d,refresh,notify}){
 const props={d,refresh,notify,role};
 if(['Overview','Home'].includes(page))return <Overview {...props}/>;
 if(['Seniors','My Seniors','Assigned Seniors','My Parent'].includes(page))return <Seniors {...props}/>;
 if(page==='Families')return <Families {...props}/>;
 if(page==='Staff')return <Staff {...props}/>;
 if(page==='Visits'||page==='Today'||page==='Next Visit')return <Visits {...props}/>;
 if(page==='Requests'||page==='Request Help')return <Requests {...props}/>;
 if(page==='Health')return <Health {...props}/>;
 if(page==='Incidents'||page==='Emergency')return <Incidents {...props}/>;
 if(page==='Subscriptions'||page==='Subscription')return <Subscriptions {...props}/>;
 if(page==='Payments')return <Payments {...props}/>;
 if(page==='Reports')return <Reports {...props}/>;
 if(page==='Services')return <Services {...props}/>;
 if(page==='Notifications')return <Notifications {...props}/>;
 return <Card title={page}><div className="empty bigempty">Configuration workspace ready.</div></Card>;
}
function desc(p){return {Overview:'Live operational picture of Nityaseva.',Seniors:'Senior profiles, risk and service readiness.',Families:'Family accounts and senior relationships.',Staff:'Care team and senior assignments.',Visits:'Schedule, perform and close visits.',Requests:'Service requests from intake to closure.',Health:'Non-diagnostic readings and trends.',Incidents:'Safety events and escalation follow-up.',Emergency:'Emergency-first response workflow.',Subscriptions:'Plans, subscriptions and renewals.',Payments:'Payment and invoice records.',Reports:'Family and operational reporting.',Services:'Service master, scope and pricing.',Notifications:'In-app family and care-team alerts.',Today:'Your care work for today.', 'My Seniors':'Seniors assigned to you.','Assigned Seniors':'Seniors assigned to you.','My Parent':'Your linked senior profile.','Next Visit':'Upcoming care visit.','Request Help':'Create a care request.','Subscription':'Your active care subscription.'}[p]||'Nityaseva care workspace.'}
function Overview({d}){const active=d.seniors.filter(s=>s.active!==false).length,today=new Date().toISOString().slice(0,10),tv=d.visits.filter(v=>v.scheduled_date===today),open=d.requests.filter(r=>!['completed','closed','cancelled'].includes(r.status)).length,red=d.seniors.filter(s=>s.risk_level==='red').length;return <><section className="grid4"><Stat label="Active seniors" value={active} hint="Care plans in service"/><Stat label="Today's visits" value={tv.length} hint="Scheduled"/><Stat label="Open requests" value={open} hint="Need action"/><Stat label="Red-risk seniors" value={red} hint="Close attention"/></section><div className="grid2"><Card title="Care pulse"><div className="pulse"><div><b>{d.seniors.length}</b><span>seniors</span></div><div><b>{d.visits.length}</b><span>visits</span></div><div><b>{d.incidents.length}</b><span>incidents</span></div></div></Card><Card title="Nityaseva promise"><p className="quote">Visit → Observe → Record → Assist → Coordinate → Escalate → Inform → Follow Up</p></Card></div><Card title="Recent seniors"><SeniorTable rows={d.seniors.slice(0,8)}/></Card></>}
function Stat({label,value,hint}){return <div className="stat"><span>{label}</span><b>{value}</b><small>{hint}</small></div>}
function Card({title,children,action}){return <section className="card"><div className="card-head"><h2>{title}</h2>{action}</div>{children}</section>}
function SeniorTable({rows,onEdit}){return <div className="table-wrap"><table><thead><tr><th>Code</th><th>Senior</th><th>Age</th><th>City</th><th>Risk</th><th>Status</th>{onEdit&&<th/>}</tr></thead><tbody>{rows.map(s=><tr key={s.id}><td>{s.customer_code||'—'}</td><td><b>{s.full_name}</b></td><td>{s.age||age(s.date_of_birth)||'—'}</td><td>{s.city||'—'}</td><td><Risk v={s.risk_level}/></td><td><Badge v={s.active===false?'inactive':'active'}/></td>{onEdit&&<td><button className="tiny" onClick={()=>onEdit(s)}>Edit</button></td>}</tr>)}{!rows.length&&<tr><td colSpan="7" className="empty">No records.</td></tr>}</tbody></table></div>}
function Seniors({d,refresh,notify,role}){const [qv,setQ]=useState(''),[modal,setModal]=useState(false),[edit,setEdit]=useState(null);const rows=d.seniors.filter(s=>(s.full_name||'').toLowerCase().includes(qv.toLowerCase())||(s.customer_code||'').toLowerCase().includes(qv.toLowerCase())||(s.city||'').toLowerCase().includes(qv.toLowerCase()));const can=admin.includes(role);async function save(f){const payload={customer_code:f.customer_code||('NIT-'+Date.now().toString().slice(-6)),full_name:f.full_name,address:f.address||'',city:f.city||'Asansol',state:'West Bengal',phone:f.phone||null,gender:f.gender||null,risk_level:f.risk_level||'green',active:f.active};if(!sb){notify('Demo mode: saved locally for this session.');setModal(false);return}const r=edit?await sb.from('seniors').update(payload).eq('id',edit.id):await sb.from('seniors').insert(payload);if(r.error)notify(r.error.message);else{notify(edit?'Senior updated':'Senior created');setModal(false);setEdit(null);refresh()}}return <><div className="toolbar"><input placeholder="Search senior, code or city…" value={qv} onChange={e=>setQ(e.target.value)}/>{can&&<button className="primary" onClick={()=>{setEdit(null);setModal(true)}}>+ New senior</button>}</div><Card title={`${rows.length} senior records`}><SeniorTable rows={rows} onEdit={can?s=>{setEdit(s);setModal(true)}:null}/></Card>{modal&&<SeniorForm initial={edit} close={()=>setModal(false)} save={save}/>}</>}
function SeniorForm({initial,close,save}){const [f,setF]=useState({customer_code:'',full_name:'',phone:'',city:'Asansol',address:'',gender:'',risk_level:'green',active:true,...initial});const set=(k,v)=>setF(x=>({...x,[k]:v}));return <Modal title={initial?'Edit senior':'Add senior'} close={close}><div className="formgrid"><label>Customer code<input value={f.customer_code||''} onChange={e=>set('customer_code',e.target.value)}/></label><label>Full name<input required value={f.full_name||''} onChange={e=>set('full_name',e.target.value)}/></label><label>Phone<input value={f.phone||''} onChange={e=>set('phone',e.target.value)}/></label><label>City<input value={f.city||''} onChange={e=>set('city',e.target.value)}/></label><label>Gender<select value={f.gender||''} onChange={e=>set('gender',e.target.value)}><option value="">Select</option><option>Female</option><option>Male</option><option>Other</option></select></label><label>Risk<select value={f.risk_level||'green'} onChange={e=>set('risk_level',e.target.value)}><option>green</option><option>yellow</option><option>red</option></select></label><label className="wide">Address<textarea value={f.address||''} onChange={e=>set('address',e.target.value)}/></label></div><div className="modal-actions"><button onClick={close}>Cancel</button><button className="primary" onClick={()=>save(f)} disabled={!f.full_name}>Save</button></div></Modal>}
function Families({d}){return <Card title={`${d.families.length} family links`}><table><thead><tr><th>Senior ID</th><th>User ID</th><th>Relationship</th><th>Primary</th><th>Notifications</th></tr></thead><tbody>{d.families.map(x=><tr key={x.id}><td>{x.senior_id}</td><td>{x.user_id}</td><td>{x.relationship}</td><td>{x.is_primary?'Yes':'No'}</td><td>{x.notification_enabled?'Yes':'No'}</td></tr>)}</tbody></table><p className="muted">For production, invite/create Auth users through a secure Edge Function/Admin API. The browser should not hold a service-role key.</p></Card>}
function Staff({d}){return <Card title={`${d.staff.length} staff assignments`}><table><thead><tr><th>Senior</th><th>Staff</th><th>Role</th><th>Start</th><th>Active</th></tr></thead><tbody>{d.staff.map(x=><tr key={x.id}><td>{x.senior_id}</td><td>{x.staff_id}</td><td><Badge v={x.role}/></td><td>{x.start_date||'—'}</td><td>{x.active===false?'No':'Yes'}</td></tr>)}</tbody></table></Card>}
function Visits({d,refresh,notify,role}){const [m,setM]=useState(false),[edit,setEdit]=useState(null);const today=new Date().toISOString().slice(0,10);const rows=role==='care_executive'?d.visits.filter(v=>v.scheduled_date===today):d.visits;async function save(f){if(!sb){notify('Demo mode: visit action recorded locally only.');setM(false);return}const payload={senior_id:f.senior_id,assigned_staff_id:f.assigned_staff_id||null,scheduled_date:f.scheduled_date,scheduled_start:f.scheduled_start||null,scheduled_end:f.scheduled_end||null,visit_type:f.visit_type||'routine',status:f.status||'scheduled',notes:f.notes||null};const r=edit?await sb.from('visits').update(payload).eq('id',edit.id):await sb.from('visits').insert(payload);if(r.error)notify(r.error.message);else{notify(edit?'Visit updated':'Visit scheduled');setM(false);setEdit(null);refresh()}}return <><div className="toolbar"><span className="notice inline">{role==='care_executive'?'Today’s assigned work':'All scheduled visits'}</span>{admin.includes(role)||role==='care_manager'?<button className="primary" onClick={()=>{setEdit(null);setM(true)}}>+ Schedule visit</button>:null}</div><Card title={`${rows.length} visits`}><table><thead><tr><th>Date</th><th>Senior</th><th>Staff</th><th>Type</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(v=><tr key={v.id}><td>{v.scheduled_date}</td><td>{v.senior_id}</td><td>{v.assigned_staff_id||'—'}</td><td>{v.visit_type}</td><td><Badge v={v.status}/></td><td>{(admin.includes(role)||role==='care_manager')&&<button className="tiny" onClick={()=>{setEdit(v);setM(true)}}>Edit</button>}</td></tr>)}</tbody></table></Card>{m&&<VisitForm initial={edit} d={d} close={()=>setM(false)} save={save}/>}</>}
function VisitForm({initial,d,close,save}){const [f,setF]=useState({senior_id:'',assigned_staff_id:'',scheduled_date:new Date().toISOString().slice(0,10),scheduled_start:'10:00',scheduled_end:'11:00',visit_type:'routine',status:'scheduled',notes:'',...initial});const set=(k,v)=>setF(x=>({...x,[k]:v}));return <Modal title={initial?'Edit visit':'Schedule visit'} close={close}><div className="formgrid"><label>Senior<select value={f.senior_id||''} onChange={e=>set('senior_id',e.target.value)}><option value="">Select</option>{d.seniors.map(s=><option value={s.id} key={s.id}>{s.full_name}</option>)}</select></label><label>Assigned staff<input value={f.assigned_staff_id||''} onChange={e=>set('assigned_staff_id',e.target.value)} placeholder="Profile UUID"/></label><label>Date<input type="date" value={f.scheduled_date||''} onChange={e=>set('scheduled_date',e.target.value)}/></label><label>Start<input type="time" value={f.scheduled_start||''} onChange={e=>set('scheduled_start',e.target.value)}/></label><label>End<input type="time" value={f.scheduled_end||''} onChange={e=>set('scheduled_end',e.target.value)}/></label><label>Status<select value={f.status||'scheduled'} onChange={e=>set('status',e.target.value)}>{['scheduled','accepted','on_the_way','arrived','in_progress','completed','missed','cancelled'].map(x=><option key={x}>{x}</option>)}</select></label><label>Type<input value={f.visit_type||''} onChange={e=>set('visit_type',e.target.value)}/></label><label className="wide">Notes<textarea value={f.notes||''} onChange={e=>set('notes',e.target.value)}/></label></div><div className="modal-actions"><button onClick={close}>Cancel</button><button className="primary" onClick={()=>save(f)} disabled={!f.senior_id}>Save</button></div></Modal>}
function Requests({d,refresh,notify,role}){const [m,setM]=useState(false);async function save(f){if(!sb){notify('Demo mode: request captured locally.');setM(false);return}const r=await sb.from('service_requests').insert({senior_id:f.senior_id,title:f.title,description:f.description,priority:f.priority,category:f.category,status:'requested'});if(r.error)notify(r.error.message);else{notify('Request created');setM(false);refresh()}}return <><div className="toolbar">{(role==='family'||role==='senior'||admin.includes(role)||role==='care_manager'||role==='care_executive')&&<button className="primary" onClick={()=>setM(true)}>+ New request</button>}</div><Card title={`${d.requests.length} service requests`}><table><thead><tr><th>Senior</th><th>Title</th><th>Priority</th><th>Status</th><th>Due</th></tr></thead><tbody>{d.requests.map(r=><tr key={r.id}><td>{r.senior_id}</td><td>{r.title}</td><td><Risk v={r.priority==='critical'?'red':r.priority==='high'?'yellow':'green'}/></td><td><Badge v={r.status}/></td><td>{r.due_date?fmt(r.due_date):'—'}</td></tr>)}</tbody></table></Card>{m&&<RequestForm d={d} close={()=>setM(false)} save={save}/>}</>}
function RequestForm({d,close,save}){const [f,setF]=useState({senior_id:'',title:'',category:'Wellbeing',priority:'normal',description:''});const set=(k,v)=>setF(x=>({...x,[k]:v}));return <Modal title="New service request" close={close}><div className="formgrid"><label>Senior<select value={f.senior_id} onChange={e=>set('senior_id',e.target.value)}><option value="">Select</option>{d.seniors.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></label><label>Category<input value={f.category} onChange={e=>set('category',e.target.value)}/></label><label>Title<input value={f.title} onChange={e=>set('title',e.target.value)}/></label><label>Priority<select value={f.priority} onChange={e=>set('priority',e.target.value)}><option>low</option><option>normal</option><option>high</option><option>critical</option></select></label><label className="wide">Description<textarea value={f.description} onChange={e=>set('description',e.target.value)}/></label></div><div className="modal-actions"><button onClick={close}>Cancel</button><button className="primary" onClick={()=>save(f)} disabled={!f.senior_id||!f.title}>Submit</button></div></Modal>}
function Health({d,refresh,notify}){const [m,setM]=useState(false);async function save(f){if(!sb){notify('Demo mode: reading captured locally.');setM(false);return}const r=await sb.from('health_readings').insert({senior_id:f.senior_id,reading_type:'routine',systolic:n(f.systolic),diastolic:n(f.diastolic),pulse:n(f.pulse),spo2:n(f.spo2),temperature:n(f.temperature),glucose:n(f.glucose),weight:n(f.weight),notes:f.notes||null});if(r.error)notify(r.error.message);else{notify('Health reading recorded');setM(false);refresh()}}return <><div className="toolbar"><button className="primary" onClick={()=>setM(true)}>+ Record reading</button></div><Card title={`${d.health.length} readings`}><table><thead><tr><th>Senior</th><th>BP</th><th>Pulse</th><th>SpO2</th><th>Temp</th><th>Glucose</th><th>Recorded</th></tr></thead><tbody>{d.health.map(h=><tr key={h.id}><td>{h.senior_id}</td><td>{h.systolic||'—'}/{h.diastolic||'—'}</td><td>{h.pulse||'—'}</td><td>{h.spo2||'—'}</td><td>{h.temperature||'—'}</td><td>{h.glucose||'—'}</td><td>{fmt(h.recorded_at)}</td></tr>)}</tbody></table><p className="muted">Readings are recorded for observation and escalation. Nityaseva does not diagnose or prescribe.</p></Card>{m&&<HealthForm d={d} close={()=>setM(false)} save={save}/>}</>}
function HealthForm({d,close,save}){const [f,setF]=useState({senior_id:'',systolic:'',diastolic:'',pulse:'',spo2:'',temperature:'',glucose:'',weight:'',notes:''});const set=(k,v)=>setF(x=>({...x,[k]:v}));return <Modal title="Record health reading" close={close}><div className="formgrid"><label>Senior<select value={f.senior_id} onChange={e=>set('senior_id',e.target.value)}><option value="">Select</option>{d.seniors.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></label><label>Systolic<input type="number" value={f.systolic} onChange={e=>set('systolic',e.target.value)}/></label><label>Diastolic<input type="number" value={f.diastolic} onChange={e=>set('diastolic',e.target.value)}/></label><label>Pulse<input type="number" value={f.pulse} onChange={e=>set('pulse',e.target.value)}/></label><label>SpO2<input type="number" value={f.spo2} onChange={e=>set('spo2',e.target.value)}/></label><label>Temperature<input type="number" step="0.1" value={f.temperature} onChange={e=>set('temperature',e.target.value)}/></label><label>Glucose<input type="number" value={f.glucose} onChange={e=>set('glucose',e.target.value)}/></label><label>Weight<input type="number" step="0.1" value={f.weight} onChange={e=>set('weight',e.target.value)}/></label><label className="wide">Notes<textarea value={f.notes} onChange={e=>set('notes',e.target.value)}/></label></div><div className="modal-actions"><button onClick={close}>Cancel</button><button className="primary" onClick={()=>save(f)} disabled={!f.senior_id}>Save</button></div></Modal>}
function Incidents({d,refresh,notify}){const [m,setM]=useState(false);async function save(f,emergency=false){if(!sb){notify('Demo mode: incident captured locally.');setM(false);return}if(emergency){const r=await sb.from('emergency_events').insert({senior_id:f.senior_id,event_type:f.incident_type,emergency_service_called:false,family_contacted:false,status:'active'});if(r.error)notify(r.error.message);else notify('Emergency event opened. Call emergency services immediately when life-threatening.')}else{const r=await sb.from('incidents').insert({senior_id:f.senior_id,incident_type:f.incident_type,severity:f.severity,description:f.description,action_taken:f.action_taken,emergency_called:f.emergency_called,family_notified:f.family_notified});if(r.error)notify(r.error.message);else notify('Incident recorded')}setM(false);refresh()}return <><div className="toolbar"><button className="danger" onClick={()=>setM(true)}>+ Emergency / incident</button></div><Card title="Incidents"><table><thead><tr><th>Senior</th><th>Type</th><th>Severity</th><th>Description</th><th>Emergency</th><th>Created</th></tr></thead><tbody>{d.incidents.map(i=><tr key={i.id}><td>{i.senior_id}</td><td>{i.incident_type}</td><td><Risk v={i.severity==='critical'||i.severity==='high'?'red':i.severity==='medium'?'yellow':'green'}/></td><td>{i.description}</td><td>{i.emergency_called?'Yes':'No'}</td><td>{fmt(i.created_at)}</td></tr>)}</tbody></table></Card>{m&&<IncidentForm d={d} close={()=>setM(false)} save={save}/>}</>}
function IncidentForm({d,close,save}){const [f,setF]=useState({senior_id:'',incident_type:'Fall',severity:'medium',description:'',action_taken:'',emergency_called:false,family_notified:false});const set=(k,v)=>setF(x=>({...x,[k]:v}));return <Modal title="Emergency / incident" close={close}><div className="emergency-box"><b>Emergency-first rule:</b> If life-threatening, call 112 or appropriate emergency services immediately. Do not wait for Nityaseva approval.</div><div className="formgrid"><label>Senior<select value={f.senior_id} onChange={e=>set('senior_id',e.target.value)}><option value="">Select</option>{d.seniors.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></label><label>Type<input value={f.incident_type} onChange={e=>set('incident_type',e.target.value)}/></label><label>Severity<select value={f.severity} onChange={e=>set('severity',e.target.value)}><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label className="check"><input type="checkbox" checked={f.emergency_called} onChange={e=>set('emergency_called',e.target.checked)}/> Emergency services called</label><label className="check"><input type="checkbox" checked={f.family_notified} onChange={e=>set('family_notified',e.target.checked)}/> Family notified</label><label className="wide">Description<textarea value={f.description} onChange={e=>set('description',e.target.value)}/></label><label className="wide">Action taken<textarea value={f.action_taken} onChange={e=>set('action_taken',e.target.value)}/></label></div><div className="modal-actions"><button onClick={close}>Cancel</button><button className="danger" onClick={()=>save(f,true)} disabled={!f.senior_id}>Open emergency</button><button className="primary" onClick={()=>save(f,false)} disabled={!f.senior_id||!f.description}>Record incident</button></div></Modal>}
function Subscriptions({d}){return <><Card title="Plans"><div className="plan-grid">{d.plans.map(p=><div className="plan" key={p.id}><b>{p.name||p.code}</b><strong>₹{Number(p.single_price||0).toLocaleString('en-IN')} <small>/ single</small></strong><span>₹{Number(p.couple_price||0).toLocaleString('en-IN')} / couple</span><Badge v={p.active===false?'inactive':'active'}/></div>)}</div></Card><Card title={`${d.subscriptions.length} subscriptions`}><table><thead><tr><th>Senior</th><th>Family</th><th>Plan</th><th>Amount</th><th>Status</th><th>Renewal</th></tr></thead><tbody>{d.subscriptions.map(s=><tr key={s.id}><td>{s.senior_id}</td><td>{s.family_account_id||'—'}</td><td>{s.plan_id}</td><td>₹{Number(s.amount||0).toLocaleString('en-IN')}</td><td><Badge v={s.status}/></td><td>{s.renewal_date||'—'}</td></tr>)}</tbody></table></Card></>}
function Payments({d}){const total=d.payments.reduce((a,x)=>a+Number(x.amount||0),0);return <><section className="grid4"><Stat label="Payments" value={d.payments.length} hint="Loaded records"/><Stat label="Recorded value" value={'₹'+total.toLocaleString('en-IN')} hint="All loaded"/><Stat label="Subscriptions" value={d.subscriptions.length} hint="Active + history"/><Stat label="Mode" value={sb?'Live':'Demo'} hint="Database"/></section><Card title="Payments"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Amount</th><th>Method</th><th>Status</th><th>Date</th></tr></thead><tbody>{d.payments.map(p=><tr key={p.id}><td>{p.invoice_number||'—'}</td><td>{p.customer_id||'—'}</td><td>₹{Number(p.amount||0).toLocaleString('en-IN')}</td><td>{p.payment_method||'—'}</td><td><Badge v={p.status}/></td><td>{fmt(p.payment_date||p.created_at)}</td></tr>)}</tbody></table></Card></>}
function Reports({d}){return <div className="grid2"><Card title="Operations report"><p>Active seniors: <b>{d.seniors.filter(x=>x.active!==false).length}</b></p><p>Visits: <b>{d.visits.length}</b></p><p>Requests: <b>{d.requests.length}</b></p><p>Incidents: <b>{d.incidents.length}</b></p></Card><Card title="Family report standard"><p>Wellbeing • visits • readings • services • medication support • incidents • attention required • next steps.</p><p className="muted">Reports should communicate observations and actions, not automatic diagnoses.</p></Card><Card title={`${d.reports.length} generated family reports`}><table><thead><tr><th>Senior</th><th>Type</th><th>Period</th><th>Created</th></tr></thead><tbody>{d.reports.map(r=><tr key={r.id}><td>{r.senior_id}</td><td>{r.report_type}</td><td>{r.period_start||'—'} to {r.period_end||'—'}</td><td>{fmt(r.created_at)}</td></tr>)}</tbody></table></Card></div>}
function Services({d}){return <Card title={`${d.services.length} services`}><table><thead><tr><th>Service</th><th>Code</th><th>Price</th><th>Pricing</th><th>Professional</th><th>Active</th></tr></thead><tbody>{d.services.map(x=><tr key={x.id}><td>{x.service_name||x.name}</td><td>{x.service_code||x.code}</td><td>₹{Number(x.price||x.base_price||0).toLocaleString('en-IN')}</td><td>{x.pricing_type||'—'}</td><td>{x.requires_professional?'Yes':'No'}</td><td>{x.active===false?'No':'Yes'}</td></tr>)}</tbody></table></Card>}
function Notifications({d}){return <Card title={`${d.notifications.length} notifications`}><table><thead><tr><th>Title</th><th>Message</th><th>Priority</th><th>Read</th><th>Created</th></tr></thead><tbody>{d.notifications.map(n=><tr key={n.id}><td>{n.title}</td><td>{n.message}</td><td><Badge v={n.priority}/></td><td>{n.read?'Yes':'No'}</td><td>{fmt(n.created_at)}</td></tr>)}</tbody></table></Card>}
function Modal({title,children,close}){return <div className="overlay"><div className="modal"><div className="modal-head"><h2>{title}</h2><button onClick={close}>×</button></div>{children}</div></div>}
function Risk({v}){return <span className={'risk '+(v||'green')}>{v||'green'}</span>}function Badge({v}){return <span className="badge">{String(v||'').replaceAll('_',' ')}</span>}function n(v){return v===''||v==null?null:Number(v)}function age(d){if(!d)return null;return Math.floor((Date.now()-new Date(d))/31557600000)}function fmt(x){return x?new Date(x).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—'}
createRoot(document.getElementById('root')).render(<App/>);
